"""지원하는 신한카드 상품명과 MCP enum 스키마의 단일 원본."""

from __future__ import annotations

_PARAMETER_DESCRIPTION_PREFIX = (
    "Exact Shinhan Card(신한카드) product name. Choose the closest matching value from: "
)

CREDIT_CARD_NAMES: list[str] = [
  "신한카드 On 체크",
  "신한카드 Way 체크",
  "신한카드 Pick E 체크",
  "수소차 충전할인 신한카드",
  "신한카드 Hey Young 체크",
  "국민내일배움 신한카드 Simple",
  "신한카드 Point Plan 체크",
  "신한카드 SOL글로벌 체크",
  "신한카드 알뜰More(알뜰모아)",
  "신한카드 Eats More(이츠모아)",
  "티머니 Pay & GO 신한카드",
  "신한 슈퍼SOL 체크",
  "LG U+ Bora 신한카드 Big Plus",
  "신한카드 Air Platinum#",
  "신한카드 Pick I 체크",
  "신한카드 플리(체크)",
  "신세계 신한카드",
  "신한카드 하이패스(전용) 체크",
  "신한카드 Shopping",
  "신한카드 Edu",
  "신한카드 경차사랑 Life",
  "11번가 신한카드",
  "LG U+ 스마트플랜 Plus 신한카드",
  "전통시장사랑 체크 신한카드",
  "신한카드 SOL트래블J 체크",
  "LG전자 The 구독케어 신한카드",
  "GS ALL 신한카드",
  "메리어트 본보이™ 더 베스트 신한카드",
  "신한카드 처음 체크",
  "신한카드 SOL트립앤샵 체크",
  "신한카드 Point Plan(산리오캐릭터즈)",
  "신한카드 처음",
  "신한카드 SOL Plan+",
  "SOL 메이트 신한카드 SOL Plan 체크",
  "신한카드 나라사랑카드 체크",
  "Toss One 신한카드",
  "신한카드 나라사랑카드 체크(배틀그라운드 에디션)",
  "SKT T&Life 신한카드",
  "신한카드 플리",
  "알리익스프레스 신한카드",
  "신한카드 Discount Plan",
  "신한카드 Deep Oil",
  "신한카드 EVerywhere",
  "신한카드 Mr.Life",
  "신한카드 처음 (ANNIVERSE)",
  "신한카드 ECO Plan",
  "신한카드 Deep Store",
  "코웨이 신한카드",
  "신한카드 Edu Plan+",
  "신한카드 국민행복",
  "신한카드 Haru(Hoshino Resorts)",
  "KT 가족만족 DC 신한카드",
  "배민 신한카드 밥친구",
  "신한카드 Biz Plan",
  "신한카드 B.Big(삑)",
  "신한카드 Point Plan",
  "신한카드 The CLASSIC-Y",
  "신한카드 Simple Plan",
  "K-패스 신한카드",
  "신한카드 Hi-Point Plan",
  "신한카드 Hi-Point Plan+",
  "카카오뱅크 착붙 신한카드",
  "신한카드 주거래 체크",
  "지그재그 신한카드",
  "The CLASSIC NEO",
  "신한카드 The BEST-XO",
  "신한카드 Globus",
  "신한카드 SOL트립앤J 체크",
  "신한카드 The CLASSIC Air",
  "신한카드 Air One",
  "신한카드 Simple Plan+",
  "신한카드 Discount Plan+",
  "신한카드 SOL트래블 체크",
  "신한카드 SOL트래블",
  "신한카드 나라사랑카드 체크(유나)",
  "싱가포르항공 크리스플라이어 더 베스트 신한카드",
  "CU Npay 카드",
  "LGE.COM 신한카드",
  "신한카드 Point Plan+",
  "신한카드 Deep On Platinum+"
]

_CARD_NAME_SET = set(CREDIT_CARD_NAMES)


def parameter_description() -> str:
    return _PARAMETER_DESCRIPTION_PREFIX + ", ".join(CREDIT_CARD_NAMES)
